moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_base_rot
      - joint_lower
      - joint_upper
      - joint_rotative
    #  - joint_20
    #  - joint_21
    #  - joint_23
    #  - joint_24